- clean: ['~']

- link:
    ~/.dotfiles: ""
    ~/.vim: vim/
    ~/.tmux.conf: tmux.conf
    ~/.tmux: tmux/
    ~/.zprezto: .zprezto/
    ~/.zshenv: zshenv
    ~/.zshrc: zshrc
    ~/.zprofile: zprofile
    ~/.zpreztorc: zpreztorc
    ~/.zalias: zalias
    ~/.zfunctions: zfunctions/
    ~/.rbenv/plugins: rbenv/plugins
    ~/.rbenv/default-gems: rbenv/default-gems
    ~/.gemrc: gemrc
    ~/.reek: reek

- shell:
  - [git submodule update --init --recursive, Installing submodules]
  - [git submodule foreach git pull origin master, Updating submodules]
