- clean: ["~"]

- create:
    - ~/workspace
    - ~/.config
    - ~/.config/tmux
    - ~/.config/pry
    - ~/.config/lazygit
    - ~/.tmux/plugins
    - ~/.rbenv
    - ~/.local/share
    - ~/.local/share/navi

- link:
    ~/.config/nvim: nvim/
    ~/.dotfiles: ""
    ~/.tmux.conf: tmux.conf
    ~/.tmux/plugins/tpm: tmux-plugins/tpm
    ~/.zprezto: .zprezto/
    ~/.zshenv: zshenv
    ~/.zshrc: zshrc
    ~/.zprofile: zprofile
    ~/.zpreztorc: zpreztorc
    ~/.zalias: zalias
    ~/.zfunctions: zfunctions/
    ~/.rbenv/plugins: rbenv/plugins
    ~/.rbenv/default-gems: rbenv/default-gems
    ~/.gemrc: gemrc
    ~/.reek.yml: reek.yml
    ~/.config/pry/pryrc: pryrc.rb
    ~/.config/lazygit/config.yml: lazygit.yml
    ~/.config/navi.yml: navi/navi.yml
    ~/.local/share/navi/my_cheats: navi/my_cheats/
    ~/.local/share/navi/others: "~/Library/Application\ Support/navi/cheats"
    ~/.config/alacritty.yml: alacritty.yml
# - shell:
#   - [cp -n zshenv.local.sample ~/.zshenv.local || echo]
#   - [cp -n wtf.sample.yml ~/.config/wtf/config.yml || echo]
#   - [git submodule update --init --recursive --remote, Installing submodules]
#   - [git submodule foreach git pull origin master, Updating submodules]
#   - [hash brew || /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)", Installing brew]
#   - [brew bundle]
#   - [pip3 install neovim]
