tap "homebrew/cask"
tap "homebrew/cask-versions"
tap "homebrew/cask-fonts"
tap "wtfutil/wtfutil"

# the silver search
brew "ag"
brew "awscli"
# better cat
brew "bat"
brew "delta"
brew "fzf"
brew "git"
brew "go"
brew "hub"
brew "jq"
brew "navi"
brew "neovim"
brew "nvm"
brew "openssl@1.1"
brew "python"
brew "pgcli"
brew "ranger"
brew "rbenv"
brew "ruby-build"
brew "tmux"
brew "universal-ctags"
brew "wget"
brew "wtfutil"

cask "alacritty"
cask "alfred"
cask "appcleaner"
cask "aws-vault"
cask "flux"
cask "font-ubuntumono-nerd-font-mono"
cask "licecap"
cask "slack"
cask "spectacle"
