tap "homebrew/cask"
tap "homebrew/cask-versions"
tap "homebrew/cask-fonts"
tap "wtfutil/wtfutil"

# the silver search
brew "ag"
brew "awscli"
# better cat
brew "bat"
brew "ctags"
brew "docker"
brew "docker-compose"
brew "docker-machine"
brew "git"
brew "go"
brew "hub"
brew "lastpass-cli"
brew "neovim"
brew "nvm"
brew "openssl@1.1"
brew "python"
brew "ranger"
brew "rbenv"
brew "reattach-to-user-namespace"
brew "ruby-build"
brew "tmux"
brew "wget"
brew "wtfutil"

cask "alfred"
cask "appcleaner"
cask "aws-vault"
cask "chromedriver"
cask "dash4"
cask "flux"
cask "font-ubuntumono-nerd-font-mono"
cask "gitup"
cask "google-chrome"
cask "google-photos-backup-and-sync"
cask "iterm2"
cask "licecap"
cask "slack"
cask "spectacle"
cask "virtualbox"
cask "vlc"
